<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Where_l</name>
   <tag></tag>
   <elementGuidId>f9dee917-28d6-43a9-a8bb-aa3382026930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text-input-where</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text-input-where']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d22fce71-877d-405a-b822-4419fdd10633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>59b0b960-bd5a-45c0-bbe0-8e0a9bb6e8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label-text-input-where</value>
      <webElementGuid>de314a08-d710-4087-860c-0bafa9bd1776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-input-where</value>
      <webElementGuid>4bfed8dd-738b-4f60-b309-c0191b4859e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>0b14fa68-5130-444b-a730-aee0d358b3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>District or Province in Thailand</value>
      <webElementGuid>23447c58-bd02-4e35-95ee-f8442288775c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c387ebf9-a73c-4806-8cb8-dc82bbe1a690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>text-input-where-suggestion-list</value>
      <webElementGuid>aa1daf85-c64f-4806-8310-47ac9138685e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icl-TextInput-control</value>
      <webElementGuid>d1739c0d-905b-4525-8182-2908450b72af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2b3d71ab-bad3-47c2-837e-e7dcd3b99ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-input-where&quot;)</value>
      <webElementGuid>9392547d-cc1d-487c-bd4f-df68273f3474</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-input-where']</value>
      <webElementGuid>a13df98f-ade8-4f07-a8cd-506706f1c432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='jobsearch']/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>0de1f415-6c0b-4a97-9799-8f85dc64b049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>0bbc49c5-4722-43b3-8411-51923b0b720c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text-input-where' and @name = 'l' and @placeholder = 'District or Province in Thailand']</value>
      <webElementGuid>0c1aa022-a2d1-4aac-b01d-0d383d670f22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
